name: deno
on:
  workflow_dispatch:
env:
  DENO_VERSION: "1.31.0"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }}
permissions: read-all
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443 ghcr.io:443 github.com:443 production.cloudflare.docker.com:443 registry-1.docker.io:443

      - name: Source checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2.4.1
      - name: GitHub login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          push: true
          context: ${{ github.workflow }}
          platforms: linux/amd64,linux/arm64
          #platforms: linux/amd64

          build-args: DENO_VERSION
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}, mode=max
          tags: |
            ghcr.io/${{ env.REPOSITORY }}:${{ env.DENO_VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest
