name: deno

on:
  workflow_dispatch:

env:
  DENO_VERSION: "1.30.3"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }}

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      - name: Source checkout
        uses: actions/checkout@v3

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: GitHub login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ github.workflow }}
          platforms: linux/amd64,linux/arm64
          #platforms: linux/amd64
          build-args: DENO_VERSION
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}, mode=max
          tags: |
            ghcr.io/${{ env.REPOSITORY }}:${{ env.DENO_VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest
